# Generated by Django 4.2 on 2023-05-04 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ProxyStudent",
            fields=[],
            options={
                "ordering": ["name"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("school.student",),
            managers=[
                ("str", django.db.models.manager.Manager()),
            ],
        ),
    ]
